name: Deploy app workflow
on:
  push:
    branches:
      - main
      - develop

env:
  OUTPUT_PATH: ${{ github.workspace }}/build
  NODE_VERSION: '16'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm ci

    - name: Build app (main => https://scoopinstaller.github.io)
      if: github.ref == 'refs/heads/main'
      env:
        REACT_APP_AZURESEARCH_KEY: ${{ secrets.REACT_APP_AZURESEARCH_KEY }}
        PUBLIC_URL: "https://scoopinstaller.github.io"
      run: npm run build

    - name: Build app (develop => https://scoopinstaller.github.io/scoopinstaller-dev.github.io)
      if: github.ref == 'refs/heads/develop'
      env:
        REACT_APP_AZURESEARCH_KEY: ${{ secrets.REACT_APP_AZURESEARCH_KEY }}
        PUBLIC_URL: "https://scoopinstaller.github.io/scoopinstaller-dev.github.io"
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: ${{ env.OUTPUT_PATH }}

    - name: Deploy app (main => https://scoopinstaller.github.io)
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./build

    - name: Deploy app (develop => https://scoopinstaller.github.io/scoopinstaller-dev.github.io)
      if: github.ref == 'refs/heads/develop'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GHPAGES_DEPLOY_KEY_DEV }}
        external_repository: ScoopInstaller/scoopinstaller-dev.github.io
        publish_branch: master
        publish_dir: ./build

